module Msajili

  class Constants
    MINIMUM_SUPPORTED_ANDROID_APP_VERSION = 5

    #Response codes
    RESPONSE_ERROR = 0
    RESPONSE_SUCCESS = 1
    RESPONSE_AUTH_ERROR = 2
    RESPONSE_EMAIL_TAKEN = 3
    RESPONSE_USERNAME_TAKEN = 4
    RESPONSE_INVALID_CURRENT_PASSWORD = 5 # used when changing password
    RESPONSE_INVALID_PASSWORD_RESET_TOKEN = 6
    RESPONSE_INVALID_SYNC_POINTER = 7

    #Record types
    RECORD_CATEGORY = 1
    RECORD_COMPANY = 2
    RECORD_JOB = 3
    RECORD_JOB_FIELD = 4
    RECORD_JOB_STAT = 5
  end

end
